### ISSUE TITLE
Publish APK with releases/ at Github?

### ISSUE THREAD

**Issue by IzzySoft** [Mercandj/FileSpace-Android#6]
As your app is open-source, but not listed at F-Droid: Would you mind to attach the `.apk` files to the corresponding `releases/`? It's [pretty easy to do](https://help.github.com/articles/creating-releases/), and would give folks without Playstore the chance to use your app :)

**Comment by IzzySoft** [comment]
Umm… is that a no?

**Comment by JonathanMercandalli** [comment]
Yes sorry for the delay. For security reasons, I do not want that users install apk without the check made by the play store. So I will not provide apk.

**Comment by IzzySoft** [comment]
Thanks for your reply! That's a pity, but I have to accept it. I'm not attempting to say [my repo](https://android.izzysoft.de/repo) can hold up to that, though I've got security measures in place as well (but need a place to catch the APK from), see the "Info" link on that page.

As that's obviously not a way you're willing to go: how about bringing it to the official F-Droid repo – or are there any proprietary dependencies which are show-stoppers?

**Comment by JonathanMercandalli** [comment]
Nop, I didn't try to bringing it to the official F-Droid repo. (I do not know if `there any proprietary dependencies which are show-stoppers`)

**Comment by IzzySoft** [comment]
OK, thanks for the feedback. Still sorry to read this – but was worth a try asking for. Feel free then to close this issue, as my question is answered. And nevertheless: all the best for your project! If you one day change your mind, simply update this issue once more and I can pick up where I left :wink:

**Comment by IzzySoft** [comment]
> I do not know if there any proprietary dependencies which are show-stoppers

Well, unfortunately there are:

    compile 'com.google.android.gms:play-services-cast:10.0.1'
    compile 'com.google.android.gms:play-services-analytics:10.0.1'
    compile 'com.google.android.gms:play-services-ads:10.0.1'
    compile 'com.google.android.gms:play-services-wearable:10.0.1'
    compile 'com.google.android.gms:play-services-identity:10.0.1'
    compile 'com.google.android.gms:play-services-gcm:10.0.1'
    compile 'com.google.android.gms:play-services-plus:10.0.1'
    compile 'com.google.android.gms:play-services-maps:10.0.1'
    compile 'com.google.android.gms:play-services-auth:10.0.1'
    compile('com.crashlytics.sdk.android:crashlytics:2.5.6@aar') { …
    apply plugin: 'com.google.gms.google-services'

Wouldn't be a show-stopper for my repo – but you wrote that's not an option for you. My offer still stands, though I'm closing this issue now: feel free to re-open if you should change your mind :wink:

**Comment by Mercandj** [comment]
Thanks @IzzySoft.
It takes time, but you're right, I changed my mind and release the `APK`s [here](https://github.com/Mercandj/file-android/releases/) in a zip file because github do not support `APK`s files in comment. (it's a new project because I re-write the all apps)
Why? Easier to obtain on a phone without play services and I prefer provide apk than have to download the apk on website like aptoide... And I realised that it's difficult to build an old app that contains old deps with modern version of IDE up-to-date...
Thks again.

**Comment by IzzySoft** [comment]
Great! Thanks, @Mercandj – but if you read Github's help on [creating releases](https://help.github.com/articles/creating-releases/) (step 7, also look at the animated GIF) you will see that indeed you *can* attach `apk` files directly (hundreds of other projects do that as well – and I saw all kind of files attached). My updater script cannot deal with zipped APKs, so in that case I had to check manually. Could you please see whether you can fix that?

I've meanwhile [added your app to my repo](https://apt.izzysoft.de/fdroid/index/apk/com.mercandalli.android.apps.files), setting updates to manual (which means "irregularly checked for"). If you manage to attach the "plain `.apk` let me know, and I can switch that to automatic – which then means an update appears in my repo within 24h after your attaching it to a new release.

**Comment by Mercandj** [comment]
Again, you're right @IzzySoft, I added APKs (as binary files, it's work!) Thks =)

(I have version name in the file name, I hope you script handle that to have auto update)

**Comment by IzzySoft** [comment]
I'm confused: while the ZIP contained a version dated 5/2018, the latest release I see at `https://github.com/Mercandj/FileSpace-Android/releases` is v1.0.28 from 9/2016 – and no APK attached anywhere? That really seems to be the last tag, as `https://github.com/Mercandj/FileSpace-Android/releases/latest` resolves exactly there.

As for the file name: name it whatever you like, as long as it's attached to the latest release (tag) it will be found.

**Comment by Mercandj** [comment]
Yep I know, I deprecated this repository `FileSpace-Android` and re-write the all app in `file-android` repo. You can see the APKs here https://github.com/Mercandj/file-android/releases/

Ok for the file names, nice!

**Comment by IzzySoft** [comment]
Ah! Now I see. And you even pointed it out in this repo's description :+1:

OK, updated the Metadata here again, and switched your app to "auto-update". In about an hour we will know if it works, as then the update run should be completed.

As for file names: if one day you decide to have multiple `.apk` files attached to a release, please let me know – and make sure each one has a destinctive name part, so my updater can tell them apart :wink:

PS: somehow the license got lost? Neither repo names any. AFAIR it was GPL-3?

**Comment by Mercandj** [comment]
Ok cool.

Good to know for the multi APK split.

License: yes, it was GPL-3

**Comment by IzzySoft** [comment]
Looks fine so far, I saw no errors in the log (in fact not even a notice on your app, so the check went smooth). Next release will tell the final result, but I expect no difficulties.

Thanks for re-adding the license!

**Comment by IzzySoft** [comment]
Just to confirm: today's update was automatically fetched :+1:
